"""Vicarius vRx MCP tools for domain: aggregation.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="aggregation_group", description="aggregation \u00b7 POST /aggregation/group \u2014 Group objects by stuff. Required: metricActionName, metricAnalyticsEventAction, q, from, size, group.")
    async def aggregation_group(
        metricActionName: Annotated[str | None, Field(default=None, description="query param metricActionName (str)")] = None,
        metricAnalyticsEventAction: Annotated[str | None, Field(default=None, description="query param metricAnalyticsEventAction (str)")] = None,
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        sortOriginalModelFields: Annotated[str | None, Field(default=None, description="query param sortOriginalModelFields (str)")] = None,
        includeOriginalDoc: Annotated[bool | None, Field(default=None, description="query param includeOriginalDoc (bool)")] = None,
        includeOriginalDocIdOnly: Annotated[bool | None, Field(default=None, description="query param includeOriginalDocIdOnly (bool)")] = None,
        includeAllNestedAggregations: Annotated[bool | None, Field(default=None, description="query param includeAllNestedAggregations (bool)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        group: Annotated[str | None, Field(default=None, description="query param group (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/aggregation/group", path_params={}, query={"metricActionName": metricActionName, "metricAnalyticsEventAction": metricAnalyticsEventAction, "q": q, "sort": sort, "sortOriginalModelFields": sortOriginalModelFields, "includeOriginalDoc": includeOriginalDoc, "includeOriginalDocIdOnly": includeOriginalDocIdOnly, "includeAllNestedAggregations": includeAllNestedAggregations, "from": from_, "size": size, "group": group}, body=body)

    @mcp.tool(name="aggregation_search_group", description="aggregation \u00b7 POST /aggregation/searchGroup \u2014 Group objects by stuff. Required: objectName, q, from, size, group.")
    async def aggregation_search_group(
        objectName: Annotated[str | None, Field(default=None, description="query param objectName (str)")] = None,
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        includeOriginalDoc: Annotated[bool | None, Field(default=None, description="query param includeOriginalDoc (bool)")] = None,
        excludeFields: Annotated[str | None, Field(default=None, description="query param excludeFields (str)")] = None,
        includeFields: Annotated[str | None, Field(default=None, description="query param includeFields (str)")] = None,
        sumLastSubAggregationBuckets: Annotated[int | None, Field(default=None, description="query param sumLastSubAggregationBuckets (int)")] = None,
        subAggregationLevel: Annotated[int | None, Field(default=None, description="query param subAggregationLevel (int)")] = None,
        newParser: Annotated[bool | None, Field(default=None, description="query param newParser (bool)")] = None,
        minDocCount: Annotated[int | None, Field(default=None, description="query param minDocCount (int)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        group: Annotated[str | None, Field(default=None, description="query param group (str)")] = None,
        totalBy: Annotated[str | None, Field(default=None, description="query param totalBy (str)")] = None,
        aggrUseMaxSize: Annotated[bool | None, Field(default=None, description="query param aggrUseMaxSize (bool)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/aggregation/searchGroup", path_params={}, query={"objectName": objectName, "q": q, "sort": sort, "includeOriginalDoc": includeOriginalDoc, "excludeFields": excludeFields, "includeFields": includeFields, "sumLastSubAggregationBuckets": sumLastSubAggregationBuckets, "subAggregationLevel": subAggregationLevel, "newParser": newParser, "minDocCount": minDocCount, "from": from_, "size": size, "group": group, "totalBy": totalBy, "aggrUseMaxSize": aggrUseMaxSize}, body=body)
