"""Vicarius vRx MCP tools for domain: automations.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="automations_automations", description="automations \u00b7 GET /v1/automations \u2014 Returns list of automations")
    async def automations_automations(
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        dateFrom: Annotated[int | None, Field(default=None, description="query param dateFrom (int)")] = None,
        dateTo: Annotated[int | None, Field(default=None, description="query param dateTo (int)")] = None,
        automationNextExecutionTimeFrom: Annotated[int | None, Field(default=None, description="query param automationNextExecutionTimeFrom (int)")] = None,
        automationNextExecutionTimeTo: Annotated[int | None, Field(default=None, description="query param automationNextExecutionTimeTo (int)")] = None,
        automationTypeIn: Annotated[Any | None, Field(default=None, description="query param automationTypeIn (Any)")] = None,
        automationTypeNotIn: Annotated[Any | None, Field(default=None, description="query param automationTypeNotIn (Any)")] = None,
        automationStateNames: Annotated[Any | None, Field(default=None, description="query param automationStateNames (Any)")] = None,
        automationStepActionsIn: Annotated[Any | None, Field(default=None, description="query param automationStepActionsIn (Any)")] = None,
        automationStepActionsNotIn: Annotated[Any | None, Field(default=None, description="query param automationStepActionsNotIn (Any)")] = None,
        automationIsActive: Annotated[bool | None, Field(default=None, description="query param automationIsActive (bool)")] = None,
        automationName: Annotated[str | None, Field(default=None, description="query param automationName (str)")] = None,
        automationIdIn: Annotated[Any | None, Field(default=None, description="query param automationIdIn (Any)")] = None,
        automationIdNotIn: Annotated[Any | None, Field(default=None, description="query param automationIdNotIn (Any)")] = None,
    ) -> Any:
        return await execute_request("GET", "/v1/automations", path_params={}, query={"from": from_, "size": size, "sort": sort, "dateFrom": dateFrom, "dateTo": dateTo, "automationNextExecutionTimeFrom": automationNextExecutionTimeFrom, "automationNextExecutionTimeTo": automationNextExecutionTimeTo, "automationTypeIn": automationTypeIn, "automationTypeNotIn": automationTypeNotIn, "automationStateNames": automationStateNames, "automationStepActionsIn": automationStepActionsIn, "automationStepActionsNotIn": automationStepActionsNotIn, "automationIsActive": automationIsActive, "automationName": automationName, "automationIdIn": automationIdIn, "automationIdNotIn": automationIdNotIn}, body=None)

    @mcp.tool(name="automations_automations_2", description="automations \u00b7 GET /v1/automations/{id} \u2014 Returns automation by id")
    async def automations_automations_2(
        id: Annotated[int, Field(description="path param id")],
    ) -> Any:
        return await execute_request("GET", "/v1/automations/{id}", path_params={"id": id}, query={}, body=None)

    # --- Mutating tools (registered only when not read_only) ---
    if not read_only:
        @mcp.tool(name="automations_automations_1", description="automations \u00b7 POST /v1/automations \u2014 Inserts automation")
        async def automations_automations_1(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("POST", "/v1/automations", path_params={}, query={}, body=body)
        @mcp.tool(name="automations_automations_3", description="automations \u00b7 PUT /v1/automations/{id} \u2014 Updates automation")
        async def automations_automations_3(
            id: Annotated[int, Field(description="path param id")],
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("PUT", "/v1/automations/{id}", path_params={"id": id}, query={}, body=body)
        @mcp.tool(name="automations_update_state", description="automations \u00b7 PUT /v1/automations/{id}/updateState \u2014 Updates automation state")
        async def automations_update_state(
            id: Annotated[int, Field(description="path param id")],
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("PUT", "/v1/automations/{id}/updateState", path_params={"id": id}, query={}, body=body)
