"""Vicarius vRx MCP tools for domain: date.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Any

from fastmcp import FastMCP

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="date_get_current_date", description="date \u00b7 GET /date/getCurrentDate \u2014 Get current date.")
    async def date_get_current_date(
    ) -> Any:
        return await execute_request("GET", "/date/getCurrentDate", path_params={}, query={}, body=None)
