"""Vicarius vRx MCP tools for domain: endpoint.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="endpoint_search", description="Search endpoints (assets). RSQL `q` filter, e.g. q=endpointName=='HOST01'. size<=500, from<=10000; use sort + seek paging beyond 10000. Required: q, from, size.")
    async def endpoint_search(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        group: Annotated[str | None, Field(default=None, description="query param group (str)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        includeFields: Annotated[str | None, Field(default=None, description="query param includeFields (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/endpoint/search", path_params={}, query={"q": q, "sort": sort, "group": group, "from": from_, "size": size, "includeFields": includeFields}, body=body)

    # --- Mutating tools (registered only when not read_only) ---
    if not read_only:
        @mcp.tool(name="endpoint_delete", description="endpoint \u00b7 DELETE /endpoint/delete \u2014 Disable instance of the object. Requires a JSON request body.")
        async def endpoint_delete(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("DELETE", "/endpoint/delete", path_params={}, query={}, body=body)
        @mcp.tool(name="endpoint_delete_many", description="endpoint \u00b7 DELETE /endpoint/deleteMany \u2014 Disable instance of the objects. Required: q. Requires a JSON request body.")
        async def endpoint_delete_many(
            q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("DELETE", "/endpoint/deleteMany", path_params={}, query={"q": q}, body=body)
