"""Vicarius vRx MCP tools for domain: external_reference_external_references.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="external_reference_external_references_search_by_fields", description="external_reference_external_references \u00b7 POST /externalReferenceExternalReferences/searchByFields \u2014 Get object by connection.")
    async def external_reference_external_references_search_by_fields(
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        enabled: Annotated[bool | None, Field(default=None, description="query param enabled (bool)")] = None,
        addCount: Annotated[bool | None, Field(default=None, description="query param addCount (bool)")] = None,
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        groupBy: Annotated[str | None, Field(default=None, description="query param groupBy (str)")] = None,
        includeFields: Annotated[Any | None, Field(default=None, description="query param includeFields (Any)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/externalReferenceExternalReferences/searchByFields", path_params={}, query={"from": from_, "size": size, "enabled": enabled, "addCount": addCount, "q": q, "sort": sort, "groupBy": groupBy, "includeFields": includeFields}, body=body)

    # --- Mutating tools (registered only when not read_only) ---
    if not read_only:
        @mcp.tool(name="external_reference_external_references_search_by_objects", description="external_reference_external_references \u00b7 POST /externalReferenceExternalReferences/searchByObjects \u2014 Get object by connection.")
        async def external_reference_external_references_search_by_objects(
            enabled: Annotated[bool | None, Field(default=None, description="query param enabled (bool)")] = None,
            from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
            size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
            q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("POST", "/externalReferenceExternalReferences/searchByObjects", path_params={}, query={"enabled": enabled, "from": from_, "size": size, "q": q}, body=body)
