"""Vicarius vRx MCP tools for domain: organization_endpoint_publisher_operating_systems.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="organization_endpoint_publisher_operating_systems_locate_object_position", description="organization_endpoint_publisher_operating_systems \u00b7 GET /organizationEndpointPublisherOperatingSystems/locateObjectPosition \u2014 Returns events")
    async def organization_endpoint_publisher_operating_systems_locate_object_position(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        positionQuery: Annotated[str | None, Field(default=None, description="query param positionQuery (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
    ) -> Any:
        return await execute_request("GET", "/organizationEndpointPublisherOperatingSystems/locateObjectPosition", path_params={}, query={"q": q, "positionQuery": positionQuery, "sort": sort}, body=None)

    @mcp.tool(name="organization_endpoint_publisher_operating_systems_search", description="organization_endpoint_publisher_operating_systems \u00b7 POST /organizationEndpointPublisherOperatingSystems/search \u2014 Returns events")
    async def organization_endpoint_publisher_operating_systems_search(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        group: Annotated[str | None, Field(default=None, description="query param group (str)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        includeFields: Annotated[str | None, Field(default=None, description="query param includeFields (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/organizationEndpointPublisherOperatingSystems/search", path_params={}, query={"q": q, "sort": sort, "group": group, "from": from_, "size": size, "includeFields": includeFields}, body=body)
