"""Vicarius vRx MCP tools for domain: organization_endpoint_group.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="organization_endpoint_group_search", description="organization_endpoint_group \u00b7 POST /organizationEndpointGroup/search \u2014 Returns events")
    async def organization_endpoint_group_search(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        group: Annotated[str | None, Field(default=None, description="query param group (str)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        includeFields: Annotated[str | None, Field(default=None, description="query param includeFields (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/organizationEndpointGroup/search", path_params={}, query={"q": q, "sort": sort, "group": group, "from": from_, "size": size, "includeFields": includeFields}, body=body)

    @mcp.tool(name="organization_endpoint_group_search_by_fields", description="organization_endpoint_group \u00b7 POST /organizationEndpointGroup/searchByFields \u2014 Get object by connection.")
    async def organization_endpoint_group_search_by_fields(
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        enabled: Annotated[bool | None, Field(default=None, description="query param enabled (bool)")] = None,
        addCount: Annotated[bool | None, Field(default=None, description="query param addCount (bool)")] = None,
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        groupBy: Annotated[str | None, Field(default=None, description="query param groupBy (str)")] = None,
        includeFields: Annotated[Any | None, Field(default=None, description="query param includeFields (Any)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/organizationEndpointGroup/searchByFields", path_params={}, query={"from": from_, "size": size, "enabled": enabled, "addCount": addCount, "q": q, "sort": sort, "groupBy": groupBy, "includeFields": includeFields}, body=body)

    # --- Mutating tools (registered only when not read_only) ---
    if not read_only:
        @mcp.tool(name="organization_endpoint_group_delete", description="organization_endpoint_group \u00b7 DELETE /organizationEndpointGroup/delete \u2014 Disable instance of the object.")
        async def organization_endpoint_group_delete(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("DELETE", "/organizationEndpointGroup/delete", path_params={}, query={}, body=body)
        @mcp.tool(name="organization_endpoint_group_insert", description="organization_endpoint_group \u00b7 PUT /organizationEndpointGroup/insert \u2014 insert instance of the object")
        async def organization_endpoint_group_insert(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("PUT", "/organizationEndpointGroup/insert", path_params={}, query={}, body=body)
        @mcp.tool(name="organization_endpoint_group_update", description="organization_endpoint_group \u00b7 POST /organizationEndpointGroup/update \u2014 Update instance of the object")
        async def organization_endpoint_group_update(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("POST", "/organizationEndpointGroup/update", path_params={}, query={}, body=body)
