"""Vicarius vRx MCP tools for domain: patch_package.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="patch_package_search_by_fields", description="patch_package \u00b7 POST /patchPackage/searchByFields \u2014 Get object by connection. Required: from, size, q.")
    async def patch_package_search_by_fields(
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        enabled: Annotated[bool | None, Field(default=None, description="query param enabled (bool)")] = None,
        addCount: Annotated[bool | None, Field(default=None, description="query param addCount (bool)")] = None,
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        groupBy: Annotated[str | None, Field(default=None, description="query param groupBy (str)")] = None,
        includeFields: Annotated[Any | None, Field(default=None, description="query param includeFields (Any)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/patchPackage/searchByFields", path_params={}, query={"from": from_, "size": size, "enabled": enabled, "addCount": addCount, "q": q, "sort": sort, "groupBy": groupBy, "includeFields": includeFields}, body=body)
