"""Vicarius vRx MCP tools for domain: patch_management.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="patch_management_patch", description="List patches. REQUIRED: `softwareType` \u2014 must be 'APP' or 'OS'. Also accepts `searchQueries` (array of join filters), `q` (RSQL), and `from`/`size`. Results are in serverResponseObject.")
    async def patch_management_patch(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        searchQueries: Annotated[Any | None, Field(default=None, description="query param searchQueries (Any)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        patchIds: Annotated[Any | None, Field(default=None, description="query param patchIds (Any)")] = None,
        externalPatchIds: Annotated[Any | None, Field(default=None, description="query param externalPatchIds (Any)")] = None,
        softwareType: Annotated[str | None, Field(default=None, description="query param softwareType (str)")] = None,
    ) -> Any:
        return await execute_request("GET", "/patchManagement/patch", path_params={}, query={"q": q, "searchQueries": searchQueries, "from": from_, "size": size, "patchIds": patchIds, "externalPatchIds": externalPatchIds, "softwareType": softwareType}, body=None)

    @mcp.tool(name="patch_management_patch_1", description="List patches (POST form). REQUIRED: `softwareType` \u2014 must be 'APP' or 'OS'. Also accepts `searchQueries`/`body` join filters, `q` (RSQL), and `from`/`size`.")
    async def patch_management_patch_1(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        patchIds: Annotated[Any | None, Field(default=None, description="query param patchIds (Any)")] = None,
        externalPatchIds: Annotated[Any | None, Field(default=None, description="query param externalPatchIds (Any)")] = None,
        softwareType: Annotated[str | None, Field(default=None, description="query param softwareType (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/patchManagement/patch", path_params={}, query={"q": q, "from": from_, "size": size, "patchIds": patchIds, "externalPatchIds": externalPatchIds, "softwareType": softwareType}, body=body)

    @mcp.tool(name="patch_management_cve_info", description="patch_management \u00b7 GET /patchManagement/patch/{patchId}/cveInfo \u2014 Returns CVE info for a specific patch")
    async def patch_management_cve_info(
        patchId: Annotated[int, Field(description="path param patchId")],
        source: Annotated[str | None, Field(default=None, description="query param source (str)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        showActive: Annotated[bool | None, Field(default=None, description="query param showActive (bool)")] = None,
        publisherProductHash: Annotated[str | None, Field(default=None, description="query param publisherProductHash (str)")] = None,
        publisherOperatingSystemHash: Annotated[str | None, Field(default=None, description="query param publisherOperatingSystemHash (str)")] = None,
    ) -> Any:
        return await execute_request("GET", "/patchManagement/patch/{patchId}/cveInfo", path_params={"patchId": patchId}, query={"source": source, "from": from_, "size": size, "showActive": showActive, "publisherProductHash": publisherProductHash, "publisherOperatingSystemHash": publisherOperatingSystemHash}, body=None)
