"""Vicarius vRx MCP tools for domain: publisher_product_photos.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="publisher_product_photos_redirect_to_publisher_product_photo", description="publisher_product_photos \u00b7 GET /publisherProductPhotos/redirectToPublisherProductPhoto \u2014 Redirect to the best photo we have for an application.")
    async def publisher_product_photos_redirect_to_publisher_product_photo(
        productId: Annotated[int | None, Field(default=None, description="query param productId (int)")] = None,
        publisherId: Annotated[int | None, Field(default=None, description="query param publisherId (int)")] = None,
        photoType: Annotated[str | None, Field(default=None, description="query param photoType (str)")] = None,
        httpStatus: Annotated[str | None, Field(default=None, description="query param httpStatus (str)")] = None,
        preformExternalRedirect: Annotated[bool | None, Field(default=None, description="query param preformExternalRedirect (bool)")] = None,
    ) -> Any:
        return await execute_request("GET", "/publisherProductPhotos/redirectToPublisherProductPhoto", path_params={}, query={"productId": productId, "publisherId": publisherId, "photoType": photoType, "httpStatus": httpStatus, "preformExternalRedirect": preformExternalRedirect}, body=None)
