"""Vicarius vRx MCP tools for domain: task_endpoints_event.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="task_endpoints_event_count", description="task_endpoints_event \u00b7 GET /taskEndpointsEvent/count \u2014 Count objects by stuff.")
    async def task_endpoints_event_count(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        analyticsEventAction: Annotated[str | None, Field(default=None, description="query param analyticsEventAction (str)")] = None,
        searchQuerys: Annotated[Any | None, Field(default=None, description="query param searchQuerys (Any)")] = None,
    ) -> Any:
        return await execute_request("GET", "/taskEndpointsEvent/count", path_params={}, query={"q": q, "analyticsEventAction": analyticsEventAction, "searchQuerys": searchQuerys}, body=None)

    @mcp.tool(name="task_endpoints_event_count_1", description="task_endpoints_event \u00b7 POST /taskEndpointsEvent/count \u2014 Count objects by stuff.")
    async def task_endpoints_event_count_1(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        analyticsEventAction: Annotated[str | None, Field(default=None, description="query param analyticsEventAction (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/taskEndpointsEvent/count", path_params={}, query={"q": q, "analyticsEventAction": analyticsEventAction}, body=body)

    @mcp.tool(name="task_endpoints_event_filter", description="task_endpoints_event \u00b7 POST /taskEndpointsEvent/filter \u2014 Returns events")
    async def task_endpoints_event_filter(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        analyticsEventAction: Annotated[str | None, Field(default=None, description="query param analyticsEventAction (str)")] = None,
        excludeFields: Annotated[str | None, Field(default=None, description="query param excludeFields (str)")] = None,
        includeFields: Annotated[str | None, Field(default=None, description="query param includeFields (str)")] = None,
        includeOriginalDoc: Annotated[bool | None, Field(default=None, description="query param includeOriginalDoc (bool)")] = None,
        getLegacyData: Annotated[bool | None, Field(default=None, description="query param getLegacyData (bool)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/taskEndpointsEvent/filter", path_params={}, query={"q": q, "sort": sort, "analyticsEventAction": analyticsEventAction, "excludeFields": excludeFields, "includeFields": includeFields, "includeOriginalDoc": includeOriginalDoc, "getLegacyData": getLegacyData, "from": from_, "size": size}, body=body)

    @mcp.tool(name="task_endpoints_event_task_types", description="task_endpoints_event \u00b7 GET /taskEndpointsEvent/taskTypes \u2014 Returns a list of task types")
    async def task_endpoints_event_task_types(
    ) -> Any:
        return await execute_request("GET", "/taskEndpointsEvent/taskTypes", path_params={}, query={}, body=None)
