"""Vicarius vRx MCP tools for domain: task.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    pass

    # --- Mutating tools (registered only when not read_only) ---
    if not read_only:
        @mcp.tool(name="task_update", description="task \u00b7 POST /task/update \u2014 Update instance of the object")
        async def task_update(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("POST", "/task/update", path_params={}, query={}, body=body)
