"""Vicarius vRx MCP tools for domain: user_invitation.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Edit the generator (its OVERRIDES / MUTATING_OVERRIDES maps) and regenerate.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP, *, read_only: bool) -> None:

    # --- Non-mutating tools (always registered) ---
    @mcp.tool(name="user_invitation_search", description="user_invitation \u00b7 POST /userInvitation/search \u2014 Returns events Required: q, from, size.")
    async def user_invitation_search(
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        group: Annotated[str | None, Field(default=None, description="query param group (str)")] = None,
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        includeFields: Annotated[str | None, Field(default=None, description="query param includeFields (str)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/userInvitation/search", path_params={}, query={"q": q, "sort": sort, "group": group, "from": from_, "size": size, "includeFields": includeFields}, body=body)

    @mcp.tool(name="user_invitation_search_by_fields", description="user_invitation \u00b7 POST /userInvitation/searchByFields \u2014 Get object by connection. Required: from, size, q.")
    async def user_invitation_search_by_fields(
        from_: Annotated[int | None, Field(default=None, description="query param from (int)")] = None,
        size: Annotated[int | None, Field(default=None, description="query param size (int)")] = None,
        enabled: Annotated[bool | None, Field(default=None, description="query param enabled (bool)")] = None,
        addCount: Annotated[bool | None, Field(default=None, description="query param addCount (bool)")] = None,
        q: Annotated[str | None, Field(default=None, description="query param q (str)")] = None,
        sort: Annotated[str | None, Field(default=None, description="query param sort (str)")] = None,
        groupBy: Annotated[str | None, Field(default=None, description="query param groupBy (str)")] = None,
        includeFields: Annotated[Any | None, Field(default=None, description="query param includeFields (Any)")] = None,
        body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
    ) -> Any:
        return await execute_request("POST", "/userInvitation/searchByFields", path_params={}, query={"from": from_, "size": size, "enabled": enabled, "addCount": addCount, "q": q, "sort": sort, "groupBy": groupBy, "includeFields": includeFields}, body=body)

    # --- Mutating tools (registered only when not read_only) ---
    if not read_only:
        @mcp.tool(name="user_invitation_delete", description="user_invitation \u00b7 DELETE /userInvitation/delete \u2014 Disable instance of the object. Requires a JSON request body.")
        async def user_invitation_delete(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("DELETE", "/userInvitation/delete", path_params={}, query={}, body=body)
        @mcp.tool(name="user_invitation_insert", description="user_invitation \u00b7 PUT /userInvitation/insert \u2014 insert instance of the object Requires a JSON request body.")
        async def user_invitation_insert(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("PUT", "/userInvitation/insert", path_params={}, query={}, body=body)
        @mcp.tool(name="user_invitation_insert_many", description="user_invitation \u00b7 PUT /userInvitation/insertMany \u2014 Insert instance of the object Requires a JSON request body.")
        async def user_invitation_insert_many(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("PUT", "/userInvitation/insertMany", path_params={}, query={}, body=body)
        @mcp.tool(name="user_invitation_resend", description="user_invitation \u00b7 POST /userInvitation/resend \u2014 Resend invitation Requires a JSON request body.")
        async def user_invitation_resend(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("POST", "/userInvitation/resend", path_params={}, query={}, body=body)
        @mcp.tool(name="user_invitation_update", description="user_invitation \u00b7 POST /userInvitation/update \u2014 Update instance of the object Requires a JSON request body.")
        async def user_invitation_update(
            body: Annotated[Any | None, Field(default=None, description="JSON request body")] = None,
        ) -> Any:
            return await execute_request("POST", "/userInvitation/update", path_params={}, query={}, body=body)
